/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons/$lessonId'
import { Route as FlashcardsCriarDeckRouteImport } from './routes/flashcards/criarDeck'
import { Route as FlashcardsUidRouteImport } from './routes/flashcards/$uid'
import { Route as FlashcardsDecksLessonIdRouteImport } from './routes/flashcards/decks/$lessonId'
import { Route as FlashcardsDecksUidDeckIdRouteImport } from './routes/flashcards/decks/$uid/$deckId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsCriarDeckRoute = FlashcardsCriarDeckRouteImport.update({
  id: '/flashcards/criarDeck',
  path: '/flashcards/criarDeck',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsUidRoute = FlashcardsUidRouteImport.update({
  id: '/flashcards/$uid',
  path: '/flashcards/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsDecksLessonIdRoute = FlashcardsDecksLessonIdRouteImport.update({
  id: '/flashcards/decks/$lessonId',
  path: '/flashcards/decks/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsDecksUidDeckIdRoute =
  FlashcardsDecksUidDeckIdRouteImport.update({
    id: '/flashcards/decks/$uid/$deckId',
    path: '/flashcards/decks/$uid/$deckId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/flashcards/$uid': typeof FlashcardsUidRoute
  '/flashcards/criarDeck': typeof FlashcardsCriarDeckRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/flashcards/decks/$lessonId': typeof FlashcardsDecksLessonIdRoute
  '/flashcards/decks/$uid/$deckId': typeof FlashcardsDecksUidDeckIdRoute
}
export interface FileRoutesByTo {
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/flashcards/$uid': typeof FlashcardsUidRoute
  '/flashcards/criarDeck': typeof FlashcardsCriarDeckRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/flashcards/decks/$lessonId': typeof FlashcardsDecksLessonIdRoute
  '/flashcards/decks/$uid/$deckId': typeof FlashcardsDecksUidDeckIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/flashcards/$uid': typeof FlashcardsUidRoute
  '/flashcards/criarDeck': typeof FlashcardsCriarDeckRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/flashcards/decks/$lessonId': typeof FlashcardsDecksLessonIdRoute
  '/flashcards/decks/$uid/$deckId': typeof FlashcardsDecksUidDeckIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/chat'
    | '/login'
    | '/flashcards/$uid'
    | '/flashcards/criarDeck'
    | '/lessons/$lessonId'
    | '/dashboard'
    | '/flashcards/decks/$lessonId'
    | '/flashcards/decks/$uid/$deckId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chat'
    | '/login'
    | '/flashcards/$uid'
    | '/flashcards/criarDeck'
    | '/lessons/$lessonId'
    | '/dashboard'
    | '/flashcards/decks/$lessonId'
    | '/flashcards/decks/$uid/$deckId'
  id:
    | '__root__'
    | '/chat'
    | '/login'
    | '/flashcards/$uid'
    | '/flashcards/criarDeck'
    | '/lessons/$lessonId'
    | '/dashboard/'
    | '/flashcards/decks/$lessonId'
    | '/flashcards/decks/$uid/$deckId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRoute
  LoginRoute: typeof LoginRoute
  FlashcardsUidRoute: typeof FlashcardsUidRoute
  FlashcardsCriarDeckRoute: typeof FlashcardsCriarDeckRoute
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  FlashcardsDecksLessonIdRoute: typeof FlashcardsDecksLessonIdRoute
  FlashcardsDecksUidDeckIdRoute: typeof FlashcardsDecksUidDeckIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards/criarDeck': {
      id: '/flashcards/criarDeck'
      path: '/flashcards/criarDeck'
      fullPath: '/flashcards/criarDeck'
      preLoaderRoute: typeof FlashcardsCriarDeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards/$uid': {
      id: '/flashcards/$uid'
      path: '/flashcards/$uid'
      fullPath: '/flashcards/$uid'
      preLoaderRoute: typeof FlashcardsUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards/decks/$lessonId': {
      id: '/flashcards/decks/$lessonId'
      path: '/flashcards/decks/$lessonId'
      fullPath: '/flashcards/decks/$lessonId'
      preLoaderRoute: typeof FlashcardsDecksLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards/decks/$uid/$deckId': {
      id: '/flashcards/decks/$uid/$deckId'
      path: '/flashcards/decks/$uid/$deckId'
      fullPath: '/flashcards/decks/$uid/$deckId'
      preLoaderRoute: typeof FlashcardsDecksUidDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRoute,
  LoginRoute: LoginRoute,
  FlashcardsUidRoute: FlashcardsUidRoute,
  FlashcardsCriarDeckRoute: FlashcardsCriarDeckRoute,
  LessonsLessonIdRoute: LessonsLessonIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  FlashcardsDecksLessonIdRoute: FlashcardsDecksLessonIdRoute,
  FlashcardsDecksUidDeckIdRoute: FlashcardsDecksUidDeckIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
