/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as FlashcardsIndexRouteImport } from './routes/flashcards/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons/$lessonId'
import { Route as FlashcardsCriarDeckRouteImport } from './routes/flashcards/criarDeck'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsIndexRoute = FlashcardsIndexRouteImport.update({
  id: '/flashcards/',
  path: '/flashcards/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsCriarDeckRoute = FlashcardsCriarDeckRouteImport.update({
  id: '/flashcards/criarDeck',
  path: '/flashcards/criarDeck',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/flashcards/criarDeck': typeof FlashcardsCriarDeckRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/flashcards': typeof FlashcardsIndexRoute
}
export interface FileRoutesByTo {
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/flashcards/criarDeck': typeof FlashcardsCriarDeckRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/flashcards': typeof FlashcardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/flashcards/criarDeck': typeof FlashcardsCriarDeckRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/flashcards/': typeof FlashcardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/chat'
    | '/login'
    | '/flashcards/criarDeck'
    | '/lessons/$lessonId'
    | '/dashboard'
    | '/flashcards'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chat'
    | '/login'
    | '/flashcards/criarDeck'
    | '/lessons/$lessonId'
    | '/dashboard'
    | '/flashcards'
  id:
    | '__root__'
    | '/chat'
    | '/login'
    | '/flashcards/criarDeck'
    | '/lessons/$lessonId'
    | '/dashboard/'
    | '/flashcards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRoute
  LoginRoute: typeof LoginRoute
  FlashcardsCriarDeckRoute: typeof FlashcardsCriarDeckRoute
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  FlashcardsIndexRoute: typeof FlashcardsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards/': {
      id: '/flashcards/'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards/criarDeck': {
      id: '/flashcards/criarDeck'
      path: '/flashcards/criarDeck'
      fullPath: '/flashcards/criarDeck'
      preLoaderRoute: typeof FlashcardsCriarDeckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRoute,
  LoginRoute: LoginRoute,
  FlashcardsCriarDeckRoute: FlashcardsCriarDeckRoute,
  LessonsLessonIdRoute: LessonsLessonIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  FlashcardsIndexRoute: FlashcardsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
